apiVersion: v1
kind: Service
metadata:
  name: {% raw %}{{ .Values.name }}{% endraw %}-web
  namespace: {% raw %}{{ .Values.namespace }}{% endraw %}
  labels:
    app: {% raw %}{{ .Values.name }}{% endraw %}-web
    app.kubernetes.io/name: {% raw %}{{ .Values.name }}{% endraw %}-web
spec:
  selector:
    app: {% raw %}{{ .Values.name }}{% endraw %}-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {% raw %}{{ .Values.containerPort }}{% endraw %}
  type: {% raw %}{{ .Values.service.type }}{% endraw %}
